version: '3'
services:
  proxy:
    depends_on: ['redis']
    environment:
      REDIS_HOST: redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 6333:6333
  redis:
    image: "redis"
    volumes:
      - redis:/data/db
volumes:
  redis:
